// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UI.WEB.Models
{
    public partial class Cliente1
    {
        public string Identificacion { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string FechaNacimiento { get; set; }
        public string LugarNacimiento { get; set; }
        public string Edad { get; set; }
        public string Nacionalidad { get; set; }
        public string Sexo { get; set; }
        public string Sector { get; set; }
        public string ResidenciaCalle { get; set; }
        public int? NumeroConsultas { get; set; }
        public string EstadoCivil { get; set; }
        public int? NumCreditosHistoricos { get; set; }
        public int? NumCreditosActivos { get; set; }
        public int? NumPrestamosActivas { get; set; }
        public int? NumServiciosActivas { get; set; }
        public int? NumTarjetasActivas { get; set; }
        public int? DefaultsHistoricos { get; set; }
        public int? DiasMora { get; set; }
        public int? DefaultValue { get; set; }
        public decimal? Constante { get; set; }
        public decimal? CoefNumCredActivos { get; set; }
        public decimal? CoefTasaDefaultHist { get; set; }
        public decimal? LogBase { get; set; }
        public decimal? PdBase { get; set; }
        public int? NumIncumplBase { get; set; }
        public int? DefaultEsperadoBase { get; set; }
        public int? ScoreBase { get; set; }
        public string NivelRiesgoBase { get; set; }
        public decimal? MontoMaxCredHistUs { get; set; }
        public decimal? MontoMaxCredHistDo { get; set; }
        public decimal? RangoPercentScore { get; set; }
        public decimal? LogOptimista { get; set; }
        public decimal? PdOptimista { get; set; }
        public int? NumIncumplEsperadoOptim { get; set; }
        public int? DefaultEsperadoOptim { get; set; }
        public decimal? ScoreOptimista { get; set; }
        public string NivelRiesgoOptim { get; set; }
        public decimal? LogPesimista { get; set; }
        public decimal? PdPesimista { get; set; }
        public int? NumIncumpEsperadoPesim { get; set; }
        public int? DefaultEsperadoPesim { get; set; }
        public decimal? ScorePesimista { get; set; }
        public string NivelRiesgoPesim { get; set; }
        public decimal? LimitePd { get; set; }
        public decimal? LimiteLog { get; set; }
        public decimal? FactorNumCredAct { get; set; }
        public int? LimiteNumCreditosAct { get; set; }
        public int? CupoCredNumCred { get; set; }
        public decimal? PromedioCuotaPrestamoDo { get; set; }
        public decimal? PromedioCuotaPrestamoUs { get; set; }
        public decimal? CuotaPromPrestamoDo { get; set; }
        public decimal? PromedioCuotaTarjetaDo { get; set; }
        public decimal? PromedioCuotaTarjetaUs { get; set; }
        public decimal? CuotaPromedioTarjetaDo { get; set; }
        public decimal? CuotaPromedioTotalDo { get; set; }
        public decimal? CuotaPromedioTotalUs { get; set; }
        public decimal? TipoDeCambio { get; set; }
        public decimal? CuotaPromTotalExpresDo { get; set; }
        public decimal? CuotaPromTotalExpresUs { get; set; }
        public int? CuentaActivaLegal { get; set; }
        public string FechaUltimos24Meses { get; set; }
        public int? CuentaCastigUlt24Mes { get; set; }
        public string FechaUltimos12Meses { get; set; }
        public int? Mas3Atra30DiasUltMeses { get; set; }
        public int? Mas2Atrasos60Dias { get; set; }
        public decimal? CuotaMaxTotalDo { get; set; }
        public decimal? CuotaMaxTotalUs { get; set; }
        public decimal? CuotaMinTotalDo { get; set; }
        public decimal? CuotaMinTotalUs { get; set; }
        public decimal? CuotaMinTotalExpresDo { get; set; }
        public decimal? CuotaMaxTotalExpresDo { get; set; }
        public decimal? CuotaMinTotalExpresUs { get; set; }
        public decimal? CuotaMaxTotalExpresUs { get; set; }
        public decimal? CuotaPerc50ExpresDo { get; set; }
        public decimal? CuotaPerc50ExpresUs { get; set; }
        public decimal? CuotaPerc75ExpresDo { get; set; }
        public decimal? CuotaPerc75ExpresUs { get; set; }
        public DateTime FechaCreacion { get; set; }
        public decimal? ParticipacionUnitaria { get; set; }
        public decimal? RangoPercentilScoreOptimista { get; set; }
        public decimal? RangoPercentilScorePesimista { get; set; }
        public string ScoreGanador { get; set; }
        public double? Imaereciente { get; set; }
        public double? Imaeprom12 { get; set; }
        public double? TasaIncumplimiento { get; set; }
        public string DecisionGanadora { get; set; }
        public bool FlagDecisionScore { get; set; }
        public bool FlagLimitesPolitica { get; set; }
        public int NumCastigadosActivos { get; set; }
        public int NumAtrasosMas60 { get; set; }
        public int NumPresTarjEnLegal { get; set; }
        public bool FlagCupoCreditos { get; set; }
        public DateTime FechaTrasladoHistorico { get; set; }
        public int Id { get; set; }
    }
}