// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UI.WEB.Models
{
    public partial class CredencialesCdr
    {
        public Guid UserId { get; set; }
        public string UserDc { get; set; }
        public string PassDc { get; set; }
    }
}