// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UI.WEB.Models
{
    public partial class DecisionCrediticia
    {
        public int Id { get; set; }
        public string NivelRiesgo { get; set; }
        public string DecisionBase { get; set; }
        public string DecisionOptimista { get; set; }
        public string DecisionPesimista { get; set; }
    }
}