// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UI.WEB.Models
{
    public partial class FotoCliente
    {
        public string CodigoIdentificacion { get; set; }
        public string Foto { get; set; }
        public DateTime FechaCreacion { get; set; }
        public DateTime FechaModificacion { get; set; }
    }
}