// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using UI.WEB.Models;

namespace UI.WEB.Models
{
    public partial interface IUI_ContextProcedures
    {
        Task<int> CalcularScoresAsync(string Id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> TrasladarClienteAsync(string Id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
