// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UI.WEB.Models
{
    public partial class ParametrosV
    {
        public double TipoCambio { get; set; }
        public double Imaereciente { get; set; }
        public double Imaeprom12 { get; set; }
    }
}