// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UI.WEB.Models
{
    public partial class Productos
    {
        public int Id { get; set; }
        public string Producto { get; set; }
        public string Reestriccion1 { get; set; }
        public string Reestriccion2 { get; set; }
        public string Reestriccion3 { get; set; }
        public string Reestriccion4 { get; set; }
        public string Definicion { get; set; }
        public double? MontoMinimo { get; set; }
        public int? PlazoMinimo { get; set; }
        public int? PlazoMaximo { get; set; }
        public string Garantia { get; set; }
        public double? Comision { get; set; }
        public double? TasaInteres { get; set; }
    }
}